export enum UserRole {
  PATIENT = 'PATIENT',
  DOCTOR = 'DOCTOR',
  HOSPITAL_ADMIN = 'HOSPITAL_ADMIN',
  SUPER_ADMIN = 'SUPER_ADMIN',
}

export enum OrderStatus {
  CREATED = 'CREATED',
  PENDING_PAYMENT = 'PENDING_PAYMENT',
  PAYING = 'PAYING',
  PAID = 'PAID',
  PROCESSING = 'PROCESSING',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
  REFUND_REQUESTED = 'REFUND_REQUESTED',
  REFUND_APPROVED = 'REFUND_APPROVED',
  REFUNDED = 'REFUNDED',
  PARTIAL_REFUND_REQUESTED = 'PARTIAL_REFUND_REQUESTED',
  PARTIAL_REFUND_APPROVED = 'PARTIAL_REFUND_APPROVED',
  PARTIALLY_REFUNDED = 'PARTIALLY_REFUNDED',
  CLOSED = 'CLOSED',
}

export enum OrderType {
  REGISTRATION = 'REGISTRATION',
  MEDICINE = 'MEDICINE',
  PRODUCT = 'PRODUCT',
  SERVICE = 'SERVICE',
  PACKAGE = 'PACKAGE',
  EXAMINATION = 'EXAMINATION',
  INPATIENT_DEPOSIT = 'INPATIENT_DEPOSIT',
  REHABILITATION = 'REHABILITATION',
  HOME_CARE = 'HOME_CARE',
}

export enum PaymentStatus {
  PENDING = 'PENDING',
  PROCESSING = 'PROCESSING',
  SUCCESS = 'SUCCESS',
  FAILED = 'FAILED',
  EXPIRED = 'EXPIRED',
  REFUNDING = 'REFUNDING',
  REFUNDED = 'REFUNDED',
  SETTLED = 'SETTLED',
}

export enum PaymentChannel {
  WECHAT = 'WECHAT',
  ALIPAY = 'ALIPAY',
  UNIONPAY = 'UNIONPAY',
  BANK_CARD = 'BANK_CARD',
  MOCK = 'MOCK',
}

export enum ItemType {
  SERVICE = 'SERVICE',
  PRODUCT = 'PRODUCT',
}

export enum OrderSource {
  ONLINE = 'ONLINE',
  IN_HOSPITAL = 'IN_HOSPITAL',
  DOCTOR_RECOMMEND = 'DOCTOR_RECOMMEND',
}

export enum AppointmentStatus {
  BOOKED = 'BOOKED',
  CHECKED_IN = 'CHECKED_IN',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  NO_SHOW = 'NO_SHOW',
  CANCELLED = 'CANCELLED',
}

export enum ProductType {
  MEDICINE = 'MEDICINE',
  MEDICAL_DEVICE = 'MEDICAL_DEVICE',
  HEALTH_PRODUCT = 'HEALTH_PRODUCT',
  SUPPLEMENT = 'SUPPLEMENT',
}

export enum ServiceType {
  REGISTRATION = 'REGISTRATION',
  EXAMINATION = 'EXAMINATION',
  CONSULTATION = 'CONSULTATION',
  TELEMEDICINE = 'TELEMEDICINE',
  VIP_PACKAGE = 'VIP_PACKAGE',
  HEALTH_CHECKUP = 'HEALTH_CHECKUP',
  SECOND_OPINION = 'SECOND_OPINION',
  REHABILITATION = 'REHABILITATION',
}

export enum PackageType {
  HEALTH_CHECKUP = 'HEALTH_CHECKUP',
  VIP_CARE = 'VIP_CARE',
  CHRONIC_MANAGEMENT = 'CHRONIC_MANAGEMENT',
  MATERNITY = 'MATERNITY',
}

export enum HospitalStatus {
  ACTIVE = 'ACTIVE',
  SUSPENDED = 'SUSPENDED',
  DEACTIVATED = 'DEACTIVATED',
}

export enum SubscriptionTier {
  STANDARD = 'STANDARD',
  PREMIUM = 'PREMIUM',
  ENTERPRISE = 'ENTERPRISE',
}
